baseurl: "http://www.vingaship.se/"
title: "Vinga Ship Management"
languageCode: "sv"
defaultContentLanguage: "sv"
defaultContentLanguageInSubdir: false
enableRobotsTXT: true
enableEmoji: true
MetaDataFormat: "yaml"
EnableMissingTranslationPlaceholders: true
googleAnalytics: "UA-98787355-1"

languages:
  sv:
    weight: 0
    languageName: "Svenska"
  en:
    weight: 1
    languageName: "English"

blackfriday:
  extensions:
    - hardLineBreak

params:
  address:
    street: Donsö Hamnväg 45
    zip: SE-430 82
    city: Donsö
    country: Sverige

  emails:
    - info@vingaship.se
    - technical@vingaship.se
    - personnel@vingaship.se
    - invoice@vingaship.se

  phone:
    - "+4631973392"

  partners:
    - title: Alba Tankers
      url: https://www.albatankers.com/
    - title: MariTrain AB
      url: https://www.maritrain.se/
    - title: MH Shipping Concept AB
      url: https://www.shippingconcept.se/
